// HYBRID INHERITANCE IN JAVA IS A MIXTURE OF SINGLE LEVEL INHERITANCE, MULTILEVEL INHERITANCE AND HIERARCHIAL INHERITANCE
// THIS IS JUST BASIC THEORY...PROBLEMS AND EXAMPLES WILL BE ADDED ON LATER

public class HybridInheritance
{
    public static void main(String[] args)
    {

    }
}